spring:
  datasource:
    url: jdbc:h2:mem:fejava
    username: fejava
    password:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

api:
  security:
    token:
      secret: my-secret-key

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: us-east-2
    stack:
      auto: false
    bucket:
      name: s3-menufoods
      endpoint: https://s3.us-east-2.amazonaws.com/s3-menufoods

application:
  upload:
    files:
      s3-url-format: https://s3-menufoods.s3.us-east-2.amazonaws.com
