spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
api:
  security:
    token:
      secret: ${JWT_SECRET}
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: us-east-2
    stack:
      auto: false
    bucket:
      name: s3-menufoods
      endpoint: https://s3.us-east-2.amazonaws.com/s3-menufoods
application:
  upload:
    files:
      s3-url-format: https://s3-menufoods.s3.us-east-2.amazonaws.com
