spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/postgresql-menufoods
    username: menufoods-db
    password: menufoods-db-password
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
api:
  security:
    token:
      secret: c86f61979bc19973072e238550b9d06ef8039d2374806133e7cac41734e6bc56
  path:
    url: ${upload_directory:NotFromDocker}