spring:
  datasource:
    url: jdbc:h2:mem:fejava
    username: fejava
    password:
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}